### PR TITLE
Travis tests runs

### PR DESCRIPTION
**Pull request by londumas**
new branch, fresh start with code that works!

### CODE REVIEW

**Comment by londumas** [comment]
@TEtourneau, it works. I used `2>&1 | tee` to print to the terminal and to the logs.
Can you run on Nersc, changing
```
self._test = True
```
to 
```
self._test = False
self._branchFiles = './data_test/'
```
where you ran mkdir data_test
then tell me where I can read the files.
Thanks for the help.

**Comment by londumas** [comment]
Let's have you do a review. I have not changed the code, only the tests. Then we can merge.

**Review by TEtourneau — APPROVED** [review]

**Comment by londumas** [comment]
@TEtourneau, thank you for the help

**Comment by TEtourneau** [comment]
Thank you for all the work you've been doing !

**Pull request merged**
