### PR TITLE
Add travis test

### PR DESCRIPTION
**Pull request by londumas**
Add travis test, second atempt

### CODE REVIEW

**Comment by londumas** [comment]
@jmarclegoff and @TEtourneau, I managed to make a lot of progress:
 - for python3, the test fails because of the following cosmolopy issue https://github.com/roban/CosmoloPy/issues/6: Cosmolopy has not been touched for 7 years, I wounder if it is safe to use it...
 - for python2, the code runs, but can produce a timeout at the level of `*** Running make_spectra 8 times ***`, because travis does not see any output, and thinks that the code is doing nothing, when really it is taking some time. Would it be possible to print the output both in the terminal and in the logs?

The hardest thing of the day was to know how to use `SACLAYMOCKS_BASE/etc/<files>`, which I do by setting the global environment variable from python itself in the tests.
I also tried to go lower than `--box-size 256`, I was able to use `--box-size 128`, but can not go lower in powers of two. Is there a reason?

**Comment by londumas** [comment]
@TEtourneau, can you have a look at the log `https://travis-ci.org/igmhub/SaclayMocks/builds/530100905?utm_source=github_status&utm_medium=notification`, some things seem strange, but I do not know a lot.

```
('**** WARNING rmax=', 576.2510991117462, ' while rmax >= 1000 advised ****')
```

```
Starting DrawGRF...
Specified seed is 42
('volume = ', 264328200.0)
('/home/travis/build/igmhub/SaclayMocks/py/SaclayMocks/../..//etc/wisdom.128-128-1536.64.npy', ' wisdomfile not found !!! set save_wisdom = true')
```

```
-----------------------------------------------------------
-----------------------------------------------------------
WARNING: Not loading mcmc in pyigm.fN   
 Install pymc if you want it
-----------------------------------------------------------
Using P14 spline values to generate a default model
Loading: /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pyigm/data/fN/fN_spline_z24.fits.gz
Seed has not been specified. Seed is set to 1572916739
Files will be read from /tmp/tmpJDRcnG//Products//mock_0/chunk_1/spectra_merged/
Output will be written in /tmp/tmpJDRcnG//Products//mock_0/chunk_1/dla.fits
Will read 20  files
Read 0 of 20
Fits table written.
Draw 6648 DLAs
Took 2.76520705223 s
5.30Real 4.16user 0.22system 82%CPU 151724 
```

```
Treated healpix pixels: [2496, 2497, 2498, 2499, 2500, 2501, 2502, 2503, 2504, 2505, 2506, 2507, 2508, 2509, 2510, 2511, 2512, 2513, 2514, 2515, 2516, 2517, 2518, 2519, 2520, 2521, 2522, 2523, 2524, 2525, 2526, 2527, 2528, 2529, 2530, 2531, 2532, 2533, 2534, 2535, 2536, 2537, 2538, 2539, 2540, 2541, 2542, 2543]
Reading DLA catalog...
Done. 0.133296966553 s
Getting the treated files...
Done. 0.000791788101196 s
No file found for these healpix pixels
56.78Real 1.61user 0.14system 3%CPU 103080 
```

**Comment by londumas** [comment]
[edit] Done

We could use `pip install --no-deps git+https://github.com/pyigm/pyigm.git`, it works on my computer. Need to understand how to make it work on travis.

**Comment by TEtourneau** [comment]
Concerning the output in the terminal, I found this:
https://stackoverflow.com/questions/28746046/how-can-i-install-something-on-travis-ci-without-a-timeout/28833319#28833319
So we can probably use the travis_wait command to avoid being killed. (Maybe it's not a good way to do, people are using this command to build the travis test: pip install etc, but I think it should work.)

Concerning the box size argument, in practice you could go with any size you want, but it need to be defined within the chunk_parameters() function (in submit_mocks.py)
If you think that would be useful, I can set up a very small box set of parameters, and even a travis-test option, to get run very quick (and print logs in the terminal).

Concerning the WARNING when computing the power spectrum, I have to have a look to it. 

And finaly, concerning pyigm, did you succeed in installing it on travis cluster ? There is a try in dla_saclay.py when importing pyigm. If pyigm is not found, it should load another distribution, but I think it's not working (it was set up for the London mocks)

**Comment by londumas** [comment]
Yes, can you set up so we can use 32 and 64 or even smaller if it is not
too much work?
I indeed manages to install pyigm, you can see in the requirements

**Comment by londumas** [comment]
@TEtourneau, the command does not work, I still have the following.
What about finding a way to print to a log and to the terminal?
```
No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.
Check the details on how to adjust your build configuration on: https://docs.travis-ci.com/user/common-build-problems/#Build-times-out-because-no-output-was-received
The build has been terminated
```

**Comment by TEtourneau** [comment]
What did you tried exactly ? 
Did you tried putting more time ? 
travis_wait 30 for instance

If you prefere, I can write an option --travis-test in order to put all inputs in the terminal. It will be very messy but I guess travis won't terminate the built.

**Pull request closed without merging**
