### PR TITLE
fix arg seed for dla_saclay.py

### PR DESCRIPTION
**Pull request by TEtourneau**

### CODE REVIEW

**Comment by londumas** [comment]
@TEtourneau, thanks for the PR. Still crashing.
You can test your PR on you own computer by running `python test_cor.py`
```
usage: dla_saclay.py [-h] --input_path INPUT_PATH --output_file OUTPUT_FILE
                     [--input_pattern INPUT_PATTERN] --fname_sigma FNAME_SIGMA
                     [--nmin NMIN] [--nmax NMAX] [--dla_bias DLA_BIAS]
                     [--cell_size CELL_SIZE] [--seed SEED]
dla_saclay.py: error: unrecognized arguments: -seed 42
-----------------------------------------------------------
-----------------------------------------------------------
WARNING: Not loading mcmc in pyigm.fN   
 Install pymc if you want it
-----------------------------------------------------------
Using P14 spline values to generate a default model
Loading: /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pyigm/data/fN/fN_spline_z24.fits.gz
Command exited with non-zero status 2
2.08Real 1.35user 0.11system 70%CPU 86508 
```

**Comment by TEtourneau** [comment]
Ok, I did again a correction, and it looks fine:
```
----------------------------------------------------------------------
Ran 1 test in 211.356s

OK
```

**Comment by londumas** [comment]
@TEtourneau, perfect. Let's wait for the travis test to say ok.

**Comment by londumas** [comment]
Thanks @TEtourneau, fixed:
```
-----------------------------------------------------------
-----------------------------------------------------------
WARNING: Not loading mcmc in pyigm.fN   
 Install pymc if you want it
-----------------------------------------------------------
Using P14 spline values to generate a default model
Loading: /home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/pyigm/data/fN/fN_spline_z24.fits.gz
Specified seed is 42
Files will be read from /tmp/tmp7ZM294//Products//mock_0/chunk_1/spectra_merged/
Output will be written in /tmp/tmp7ZM294//Products//mock_0/chunk_1/dla.fits
Will read 20  files
Read 0 of 20
Fits table written.
Draw 6650 DLAs
Took 5.56939578056 s
7.59Real 5.55user 0.21system 75%CPU 151648 
```

**Review by londumas — APPROVED** [review]

**Pull request merged**
