### PR TITLE
python3-compatible

### PR DESCRIPTION
**Pull request by londumas**
new division, compatible Python2.7 and Python3.
This should not produce bigs on your part, but can you check using:
`python $HOME/Programs/igmhub/SaclayMocks/bin/submit_mocks.py --mock-dir ./ --cori-nodes False --box-size 256`

### CODE REVIEW

**Comment by londumas** [comment]
@TEtourneau, let's keep this PR alive for the moment to try to get your code python2 and python3 compatible the best we can.

**Comment by londumas** [comment]
@TEtourneau, can you test this branch on your computer in python2? and do a review? Normally it should be python2 and python3 compatible.

**Comment by londumas** [comment]
@TEtourneau, can you do a review and do a simple test that it did not break anything?

**Comment by TEtourneau** [comment]
So I did a simple test:
submit_mocks.py --mock-dir . --cori-nodes False --box-size 256 --chunk-id 1

It seems to work (no python bug at least).
But we should probably use travis test, to be sure that the output is still the same ?

The test would be to produce a small realisation (command above), with some fixed seeds, and compare the output. 
Would it be possible to do it with travis ? (I'm not familiar with it)

**Comment by londumas** [comment]
@TEtourneau, I agree 100%, let's merge this branch once we have the travis tests.
I can set it up if you prefer. Could you give me the command we should run?

**Comment by londumas** [comment]
@TEtourneau, for python3.6, I went as far as I could, I hit a cosmolopy issue. Let's finish python2.7 travis tests and then work on that:
```
Traceback (most recent call last):
  File "<me>/Programs/igmhub/SaclayMocks/bin//dla_saclay.py", line 15, in <module>
    import cosmolopy.distance as dist
  File "<me>/sys/installdir/python/3.6.3/lib/python3.6/site-packages/CosmoloPy-0.1.104-py3.6-linux-x86_64.egg/cosmolopy/__init__.py", line 88, in <module>
    import constants as cc
ModuleNotFoundError: No module named 'constants'
1.71Real 1.29user 0.29system 92%CPU 65724
```

**Comment by TEtourneau** [comment]
I tried to remove the use of cosmolopy.
I managed to not use anymore the cosmology.perturbation module (I copy the only functino we were using in the `util.py library`). But there is still the use of `cosmolopy.distance` module, for the function `cosmolopy.distance.quick_distance_function()`

**Comment by londumas** [comment]
@TEtourneau, thanks. Why not using the distances the same as we do in picca?
But let's not change that in master until we have the reference files using Python2.7 and cosmolopy.

**Pull request merged**
