### PR TITLE
init travis tests (old)

### PR DESCRIPTION
**Pull request by londumas**
Add travis tests to the code.
@TEtourneau, let's work together to get these running.

### CODE REVIEW

**Comment by londumas** [comment]
@TEtourneau, here is the current output:
```
submit_mocks.py --mock-dir /tmp/tmpOONEhd//Products/ --cori-nodes False --box-size 256 --chunk-id 1

Warning: the jobs will not be sent to cori nodes, they will be executed here.
Writting scripts for 1 realisations
Mock files will be written in /tmp/tmptYrmJH//Products/
It will run:
- Pk
- Boxes
- Chunks: qso randoms make_spectra merge_spectra 
- Merge Chunks: merge_qso merge_randoms compute_dla merge_dla dla_randoms transmissions 
It will produce 1 chunks, with ids: ['1']
and ra0: ['189.982649735']
Generating script for Pk...

Generating scripts for realisation 0
Creating directory tree...
Directory tree created.
/tmp/tmptYrmJH//Products//mock_0/output/runs/submit.sh generated. Run it to submit the sbatch jobs of this realization to the cori queue
```

I get no files produced. I bet it is linked to the fact that the code wants me to run `submit.sh`.

**Comment by TEtourneau** [comment]
Yes you're right. Is that a problem ?

I just pushed a commit, to add the argument --seed
(to gt reproducible results).

How do you set up a travis test ? I would like to learn these kind of things

**Comment by londumas** [comment]
> Yes you're right. Is that a problem ?

We need a fits file to compare to a known to be good one.
Should we then run ./submit.sh? Is it going to work outside of NERSC?

> I just pushed a commit, to add the argument --seed
> (to gt reproducible results).

What should I use? `--seed 42`?

> How do you set up a travis test ? I would like to learn these kind of things

Ok, we can have a Skype when you want for me to explain that to you.

**Comment by TEtourneau** [comment]
The command for the travis test should include the argument:
--seed 10
for instance

**Comment by TEtourneau** [comment]
Skype now ? It would be much easier to set it up

**Comment by londumas** [comment]
@TEtourneau and @jmarclegoff, the code uses cosmolopy that is very old. The last commit is 7 years old: https://github.com/roban/CosmoloPy. It does not work in python3. Would it be possible to stop using it? If it is too hard, we can add that to a task list.

**Comment by TEtourneau** [comment]
I think we use cosmolopy mainly for the perturbation module (to get the growth factor).
Some time ago I began to copy the used function in the util.py library (fgrowth function for instance).
I have to check if there is other use of cosmolopy, and try to replace them, but this is not a priority I guess

**Pull request closed without merging**
